### ISSUE TITLE
Module attempts to import `src/lambda/index.ts`

### ISSUE THREAD

**Issue by kcwinner** [pahud/cdk-http-pinger#19]
When trying to synth I get the below error:
```
Cannot find entry file at .../node_modules/cdk-http-pinger/src/lambda/index.ts
Subprocess exited with error 1
🤖 Task "synth" failed when executing "cdk synth" 
```

I believe it should be `../lib/lambda/index.js` after bundling?
https://github.com/pahud/cdk-http-pinger/blob/694c9e61f9c73bcc8a5ab532a799980a26c35d9d/src/pinger.ts#L24

**Comment by pahud** [comment]
oh yes you are right. PR on the way.

cc @guan840912

**Comment by guan840912** [comment]
https://github.com/pahud/cdk-http-pinger/blob/694c9e61f9c73bcc8a5ab532a799980a26c35d9d/src/pinger.ts#L24
I think maybe need to move `lambda/index.ts` to `src/lambda/index.ts`.

and then 
```ts
entry: path.join(__dirname, './lambda/index.ts'), 
```

**Comment by pahud** [comment]
Hi @kcwinner please let me know if it works now.
